export enum VsProjectStateEnum {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
}

export enum VsCompileStatusEnum {
  COMPILING = 'COMPILING',
  QUERY_FAILED = 'QUERY_FAILED',
  COMPILE_FAILED = 'COMPILE_FAILED',
  COMPILE_SUCCESS = 'COMPILE_SUCCESS',
}
